ampserver:
    build: ampserver/
    ports:
        - "127.0.0.1:80:80"
    links:
        - database
        - rabbitmq
    volumes:        # Persistent data for www     
        - ./volumns/www:/var/www

database:
    build: mysqlDB/
    ports:
        # Bind host machine port
        - 127.0.0.1:3306:3306
    environment:
        # Root password
        MYSQL_ROOT_PASSWORD: "badboy"
        DEV_SSH_PRIVATE_KEY: "/home/spnball/.ssh/acommerce.id_rsa"
        DEV_SSH_HOST: "surapun@10.0.1.51" 
        
    volumes:        
        # Persistent data for mysql
        - ./volumns/mysql:/var/lib/mysql
        
rabbitmq:
    build: rabbitmq
    environment: 
        RABBITMQ_DEFAULT_USER: root 
        RABBITMQ_DEFAULT_PASS: badboy
    ports:
        # Bind host machine port
        # - 127.0.0.1:5672:5672
        - 127.0.0.1:15671:15671
        - 127.0.0.1:15672:15672
        - 127.0.0.1:25672:25672
